[package]
name = "crypto-finance"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.58"
linera-sdk = { path = "../linera-protocol/linera-sdk" }
linera-views = { path = "../linera-protocol/linera-views" }
thiserror = "1.0.38"

